version: '3'

services:
  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./:/var/www/
    depends_on:
      - php

  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/

  redis:
    build:
      context: ./
      dockerfile: ./docker/redis/Dockerfile
    ports:
      - 6379:6379

  sphinx:
    build:
      context: ./
      dockerfile: ./docker/sphinx/Dockerfile
    ports:
      - 9306:9306